// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "01007bf5-26b6-4f44-8f83-12feff3c4b96";

const char SSID[]               = "Jeno";    // Network SSID (name)
const char PASS[]               = "Ram lavadei";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "RZdUrWhMwfhgWkvZH5E#@d14G";    // Secret device password

void onLedChange();
void onMotionChange();
void onWaterLevelChange();
void onFirealarmChange();
void onTempChange();

CloudLight led;
CloudLight motion;
CloudLength waterLevel;
bool firealarm;
CloudTemperature temp;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(motion, READWRITE, ON_CHANGE, onMotionChange);
  ArduinoCloud.addProperty(waterLevel, READWRITE, ON_CHANGE, onWaterLevelChange);
  ArduinoCloud.addProperty(firealarm, READWRITE, ON_CHANGE, onFirealarmChange);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
